### ISSUE TITLE
QA: change in issue creator multiplier

### ISSUE THREAD

**Issue by EresDev** [web4erOrg/ubiquibot#73]
# TEST
Should generate correct the issue creator incentive for complex items in the description

initially, this issue included some descriptions, list items, and code. Look at the edit history. 
code: 5 * 1 = 5
li: 0.5 * 4 = 2
words = 97 * 0.1 = 9.7
total creator incentive = creator multiplier * incentives = 2 * (5+2+9.7) = 33.4

**Comment by web4er** [comment]
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
